# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # Backend
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    target-branch: "develop"
    labels:
      - "dependencies"
  # Frontend
  - package-ecosystem: "npm"
    directory: "/src/main/resources/static/frontend"
    schedule:
      interval: "daily"
      time: "00:00"
    target-branch: "develop"
    labels:
      - "dependencies"